"""Functions to test the functions in text.py"""
import numpy as np
from src import text


def test_cub_file_text():
    """Will test the creation of the cube file data"""
    np.random.seed(123890)

    data = np.random.random(size=(10, 10, 10))
    coords = np.random.random(size=(100, 3))
    coords[0, :] = [0.01, 0.1, 1.0]
    at_nums = np.array([6] * 100)
    origin = [0, 0, 0]
    Nvec = [10, 10, 10]
    basis_vec = [[0.3, 0.0, 0.0], [0.2, 0.1, 0.0], [0.1, 0.0, 0.1]]

    cube_file_txt = text.cube_file_text(data, coords,
                                        at_nums, origin,
                                        Nvec, basis_vec)

    assert len(cube_file_txt) == 27645
    assert cube_file_txt.count('\n') == 272
    lines = cube_file_txt.split('\n')
    assert lines[0] == 'Cube file -generated by Orbital Movie Maker'
    assert lines[1] == ''
    assert lines[2] == '100      0.000000     0.000000     0.000000'
    assert lines[3] == '10       0.300000     0.000000     0.000000'
    assert lines[4] == '10       0.200000     0.100000     0.000000'
    assert lines[5] == '10       0.100000     0.000000     0.100000'
    assert lines[6] == '6        0.000000     0.010000     0.100000     1.000000'

